implementing a margin px-5
nmunro/resourcedb pull request #29
Opened 2024-02-01 19:49 UTC by Alek20s

Hi Neil. 
I open the pull request to test the bootstrap   feature to shift text by a few pixels.
It's the absolutely  the same what Evgenij did for creating new events page.
But I did this for editing event pages.
Should I pull my changes to the production branch or the main branch?
Thank you
Alexei

2024-02-01 21:28 UTC, nmunro commented
The main branch, thanks, the main branch deploys to the test server and I manually prepare the production branch

2024-02-04 11:19 UTC, nmunro requested changes

2024-02-04 11:19 UTC, nmunro commented on info/templates/info/dashboard_event.html
> +<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="
This isn't necessary, it's already included in the base.html file: https://github.com/nmunro/resourcedb/blob/7d92f6edb269c40a93d92cf356a34e3636e7f6f7/info/templates/base.html#L9, please remove this line :)

2024-02-04 12:16 UTC, Alek20s commented
Hi Neil.Yes, I agree, this line 9  <link ***@***.***/dist/c....should be removed. I did it to be sure  we have bootstrap 5 environment. (However, in my testing server, the code didn't work without this line/ code)
    On Sunday, 4 February 2024 at 11:20:09 GMT, Neil Munro ***@***.***> wrote:  
 
 


@nmunro requested changes on this pull request.

In info/templates/info/dashboard_event.html:
> @@ -14,14 +14,14 @@
 {% endblock %}
 
 {% block content %}
-    <div class="row">
+    <div class="row px-5">
+<link ***@***.***/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

This isn't necessary, it's already included in the base.html file: https://github.com/nmunro/resourcedb/blob/7d92f6edb269c40a93d92cf356a34e3636e7f6f7/info/templates/base.html#L9, please remove this line :)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-02-24 19:17 UTC, closed without merging